sonar.projectKey=padrao-labs-agents
sonar.projectName=padrao-labs-agents
sonar.projectVersion=0.1.0

## Sources
sonar.sources=./cli/src

# Language
sonar.language=ts

# Encoding of the source files
sonar.sourceEncoding=UTF-8

# Coverage
sonar.javascript.lcov.reportPaths=./cli/coverage/lcov.info
sonar.typescript.lcov.reportPaths=./cli/coverage/lcov.info

# Exclusions
sonar.exclusions=**/*.test.ts,**/*.spec.ts,**/dist/**
sonar.coverage.exclusions=**/*.test.ts,**/*.spec.ts
