base-webapp:
  squad: comercial
  tribe: comercial
  vertical: operacoes
  product: arguinho
  replicaCount: 0
  image:
    repository: gcr.io/magalu-cicd/code-quality
    tag: v1.92.2
    pullPolicy: IfNotPresent
  command: node
  args:
    - dist/src/main.js
  resources:
    limits:
      cpu: 800m
      memory: 3Gi
    requests:
      cpu: 400m
      memory: 500Mi
  ingress:
    ingressController:
      internal:
        enabled: true
        annotations:
          konghq.com/protocol: https
          konghq.com/https-redirect-status-code: '308'
        ingressClassName: internal
        hosts:
          - host: code-quality.luizalabs.com
            paths:
              - /*
  livenessProbe:
    failureThreshold: 10
    httpGet:
      path: /
    initialDelaySeconds: 15
    periodSeconds: 20
    successThreshold: 1
    timeoutSeconds: 5
  readinessProbe:
    failureThreshold: 10
    httpGet:
      path: /health
    initialDelaySeconds: 15
    periodSeconds: 20
    successThreshold: 1
    timeoutSeconds: 5
  hpa:
    enabled: true
    targetMetric:
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 70
    minReplicas: 3
    maxReplicas: 8
  maxUnavailable: 0
  maxSurge: 1
  lifecycle:
    preStop:
      exec:
        command:
          - sleep
          - '30'
  secretFiles:
    enabled: false
  secretEnvs:
    enabled: false
  envs:
    - name: NODE_OPTIONS
      value: '--max-old-space-size=4096 --max-semi-space-size=512'
    - name: TZ
      value: America/Sao_Paulo
    - name: NODE_ENV
      value: production
    - name: PORT
      value: '5000'
    - name: GMUDID
      value: '2597'
    - name: HOSTGITLABAPI
      value: https://gitlab.luizalabs.com/api/v4
    - name: HOSTSONARAPI
      value: https://sonarqube.luizalabs.com/api
    - name: ATENA_API_URL
      value: https://atena.luizalabs.com
    - name: SECURTIFY_JOB_NAMES
      value: fortify,security,code-analysis
    - name: RELEASE_JOB_NAMES
      value: release
    - name: SONAR_JOB_NAMES
      value: sonar
    - name: GMUD_JOB_NAMES
      value: gmud
    - name: DEPLOY_JOB_NAMES
      value: deploy
    - name: ROLLBACK_JOB_NAMES
      value: rollback
    - name: DO_NOT_SILENCE_GOOGLE_APPLICATION_CREDENTIALS
      value: 'true'
    - name: CRON_TIME
      value: 0 6 * * *
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: service.tier=OTHERS
    - name: OTEL_SERVICE_NAME
      value: '[MGC] code-quality'
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://opentelemetry-collector-internal.luizalabs.com:4317
    - name: OTEL_LOG_LEVEL
      value: ERROR
    - name: OTEL_ENABLE
      value: 'false'
    - name: OTEL_TRACES_EXPORTER
      value: otlp
    - name: OTEL_METRICS_EXPORTER
      value: otlp
    - name: OTEL_EXPORTER_OTLP_HEADERS
      value: Authorization=Basic%20Z3N4LXJwa3QtcnN6OnhvcS1zc3JiLXR5bg%3D%3D
    - name: BURZUM_ENABLED
      value: 'false'
    - name: OTEL_EXPORTER_OTLP_INSECURE
      value: 'true'
    - name: CRIPTO_KEY
      value: gcp:secretmanager:projects/243428398695/secrets/CODE-QUALITY_PRD_CRIPTO_KEY/versions/1
    - name: JWT_SECRET
      value: gcp:secretmanager:projects/243428398695/secrets/CODE-QUALITY_PRD_JWT_SECRET/versions/1
    - name: BURZUM_APP_INDEX
      value: gcp:secretmanager:projects/243428398695/secrets/CODE-QUALITY_PRD_BURZUM_APP_INDEX/versions/1
    - name: GITLAB_TOKEN
      value: gcp:secretmanager:projects/243428398695/secrets/CODE-QUALITY-GITLAB_PRD_GITLAB_TOKEN/versions/2
    - name: TOKENSONARAPI
      value: gcp:secretmanager:projects/243428398695/secrets/CODE-QUALITY_PRD_TOKENSONARAPI/versions/1
    - name: DB_URL
      value: gcp:secretmanager:projects/243428398695/secrets/CODE-QUALITY_PRD_DB_URL/versions/2
    - name: ATENA_API_TOKEN
      value: gcp:secretmanager:projects/243428398695/secrets/CODE-QUALITY_PRD_ATENA_API_TOKEN/versions/1
    - name: MAPA_LABS_API_TOKEN
      value: gcp:secretmanager:projects/243428398695/secrets/CODE-QUALITY_PRD_MAPA_LABS_API_TOKEN/versions/1
    - name: REDIS_ENABLE
      value: 'true'
    - name: MAPA_LABS_API_URL
      value: https://mapa-labs-api.luizalabs.com/
    - name: REDIS_HOST
      value: 10.175.53.164
    - name: REDIS_USER
      value: usr_code_quality
    - name: REDIS_PASSWORD
      value: gcp:secretmanager:projects/243428398695/secrets/CODE-QUALITY_PRD_REDIS_PASSWORD/versions/1
    - name: GITLAB_MAX_RETRIES
      value: '30'
    - name: CONFLUENCE_HOST
      value: https://magazine.atlassian.net/wiki/api
    - name: CONFLUENCE_TOKEN
      value: gcp:secretmanager:projects/243428398695/secrets/CODE-QUALITY-GITLAB_PRD_CONFLUENCE_API_TOKEN/versions/1
    - name: LOG_LEVEL
      value: error
    - name: CODE_QUALITY_BADGES_ENABLE
      value: 'true'
    - name: MAX_CONCURRENT_OPERATIONS
      value: '10'
    - name: MAX_CONCURRENT_DB_OPERATIONS
      value: '10'
    - name: PROCESSING_CHUNK_SIZE
      value: '10'
  gmud: ''
  secretvault:
    enabled: true
  repositoryLink: https://gitlab.luizalabs.com/luizalabs/vertical-operacoes/code-quality
  author: ci-knife@luizalabs.com
  date: '2026-02-03 21:35:08'