apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: code-quality
  description: Bot de atendimento de cards da aliança backoffice
  links:
    - url: https://code-quality-mgc.luizalabs.com/
      title: URL Prod
      icon: article
      type: url-prod
    - url: https://argocd-mgc-ops-comercial.ipet.sh/applications/argocd/code-quality
      title: Argo CD Prod
      icon: article
      type: url-argocd-prod
  annotations:
    security/business-risk: Low
    security/public: Internal
    security/accessibility: No
    security/waf: No
    security/qradar: No
    security/authentication: 'Not apply'
    security/administration: 'Not apply'
    gitlab.com/project-slug: 'luizalabs/alianca-backoffice/code-quality'
    sonarqube.org/project-key: 'default/code-quality'
    argocd/app-name: code-quality
    project/service.tier: OTHERS
    backstage.io/techdocs-ref: dir:./
  tags:
    - nodejs
    - express
    - googlechat
spec:
  type: service
  lifecycle: production
  definition:
      $text: https://code-quality-mgc.luizalabs.com/swagger.json
  owner: 'group:62bcb2215ebf58b18f19c0d5' #Aliança Backoffice
  dependsOn: [
    'component:kanbanforce-api',
    'component:gitlab-api',
    'component:athena-api',
    'component:fortify',
    'resource:gitlab',
    'resource:sonarqube'
  ]
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: code-quality
  description: Kong Internal
  tags:
      - kong
spec:
  type: openapi
  lifecycle: production
  owner: 'group:62bcb2215ebf58b18f19c0d5' #Aliança Backoffice
  annotations:
    project/service.tier: OTHERS
  definition:
    $text: https://code-quality-mgc.luizalabs.com/swagger.json
  providesApis:
    - code-quality
