/**
 * Mapeamento centralizado de chaves de configuração do VS Code / Copilot.
 */
export const VSCODE_SETTINGS_KEYS = {
  INSTRUCTIONS: 'github.copilot.chat.codeGeneration.instructions',
  COPILOT_ENABLE: 'github.copilot.enable',
  PROMPT_LOCS: 'chat.promptFilesLocations',
  SKILLS_LOCS: 'chat.agentSkillsLocations',
  AGENTS_LOCS: 'chat.agentFilesLocations',
  RULES_LOCS: 'chat.instructionsFilesLocations',
  AUTOPILOT_ENABLE: 'chat.autopilot.enabled',
  IMAGE_SUPPORT: 'chat.imageSupport.enabled',
  PARENT_CUSTOMIZATIONS: 'chat.useCustomizationsInParentRepositories',
  AGENT_DEBUG_LOG: 'github.copilot.chat.agentDebugLog.enabled',
  AGENT_FILE_LOGGING: 'github.copilot.chat.agentDebugLog.fileLogging.enabled',
  TERMINAL_LINKS: 'github.copilot.chat.cli.terminalLinks.enabled',
  MCP_AUTOSTART: 'chat.mcp.autostart',
  AGENT_MAX_REQUESTS: 'chat.agent.maxRequests',
  AGENT_ENABLED: 'chat.agent.enabled',
  SESSION_PROJECTION: 'chat.agentSessionProjection.enabled',
  EXPLAIN_CHANGES: 'chat.editing.explainChanges.enabled',
  EDIT_MODE_HIDDEN: 'chat.editMode.hidden',
  SKILL_ADHERENCE: 'chat.experimental.useSkillAdherencePrompt',
  TERMINAL_AUTO_REPLY: 'chat.tools.terminal.autoReplyToPrompts',
  NESTED_AGENTS: 'chat.useNestedAgentsMdFiles',
  AGENT_AUTO_FIX: 'github.copilot.chat.agent.autoFix',
  CODESEARCH_ENABLED: 'github.copilot.chat.codesearch.enabled',
  COPILOT_MEMORY: 'github.copilot.chat.copilotMemory.enabled',
  CUSTOM_AGENT_IN_SUBAGENT: 'chat.customAgentInSubagent.enabled',
  USE_AGENT_SKILLS: 'chat.useAgentSkills',
  MEMORY_TOOLS_ENABLED: 'github.copilot.chat.tools.memory.enabled',
  GITHUB_MCP_READONLY: 'github.copilot.chat.githubMcpServer.readonly',
  FIX_TYPESCRIPT: 'github.copilot.chat.languageContext.fix.typescript.enabled',
  SWITCH_AGENT: 'github.copilot.chat.switchAgent.enabled',
  VIEW_SESSIONS_ORIENTATION: 'chat.viewSessions.orientation',
  ENABLE_CHAT_TOOLS: 'workbench.browser.enableChatTools',
  ADD_AI_COAUTHOR: 'git.addAICoAuthor',
  REQUEST_QUEUING_DEFAULT: 'chat.requestQueuing.defaultAction',
  THINKING_STYLE: 'chat.thinking.style',
  THINKING_COLLAPSED_TOOLS: 'chat.agent.thinking.collapsedTools',
  THINKING_TERMINAL_TOOLS: 'chat.agent.thinking.terminalTools',
  AUTO_EXPAND_FAILURES: 'chat.tools.autoExpandFailures',
  EXPLORE_AGENT_MODEL: 'chat.exploreAgent.defaultModel',
  NOTIFY_ON_RESPONSE: 'chat.notifyWindowOnResponseReceived',
  NOTIFY_ON_CONFIRMATION: 'chat.notifyWindowOnConfirmation',
  PLUGINS_ENABLED: 'chat.plugins.enabled',
  PLUGINS_MARKETPLACES: 'chat.plugins.marketplaces',
  PLUGINS_PATHS: 'chat.plugins.paths',
  FIND_CLOSE_ON_RESULT: 'editor.find.closeOnResult',
  PAGE_ZOOM: 'workbench.browser.pageZoom',
  AUTO_CHECK_UPDATES: 'extensions.autoCheckUpdates',
  FORMAT_ON_SAVE: 'editor.formatOnSave',
  BRACKET_COLORIZATION: 'editor.bracketPairColorization.enabled',
  BRACKET_GUIDES: 'editor.guides.bracketPairs',
  INLINE_SUGGEST: 'editor.inlineSuggest.enabled',
  COMPACT_FOLDERS: 'explorer.compactFolders',
  STARTUP_EDITOR: 'workbench.startupEditor'
} as const;

export type VSCodeSettingKey = typeof VSCODE_SETTINGS_KEYS[keyof typeof VSCODE_SETTINGS_KEYS];

/**
 * Descrições amigáveis para os logs de diff.
 */
export const SETTING_DESCRIPTIONS: Record<string, string> = {
  [VSCODE_SETTINGS_KEYS.INSTRUCTIONS]: 'Instruções globais de geração de código para o Copilot',
  [VSCODE_SETTINGS_KEYS.COPILOT_ENABLE]: 'Habilita/desabilita o Copilot por linguagem',
  [VSCODE_SETTINGS_KEYS.PROMPT_LOCS]: 'Pastas adicionais contendo arquivos de prompt (.prompt.md)',
  [VSCODE_SETTINGS_KEYS.SKILLS_LOCS]: 'Pastas contendo definições de Agent Skills',
  [VSCODE_SETTINGS_KEYS.AGENTS_LOCS]: 'Pastas contendo definições de Agentes customizados',
  [VSCODE_SETTINGS_KEYS.RULES_LOCS]: 'Pastas contendo regras (rules) de desenvolvimento',
  [VSCODE_SETTINGS_KEYS.AUTOPILOT_ENABLE]: 'Habilita o modo Autopilot no VS Code',
  [VSCODE_SETTINGS_KEYS.IMAGE_SUPPORT]: 'Habilita suporte nativo a leitura de imagens e arquivos binários',
  [VSCODE_SETTINGS_KEYS.PARENT_CUSTOMIZATIONS]: 'Descobre instruções e configurações em repositórios pai (monorepos)',
  [VSCODE_SETTINGS_KEYS.AGENT_DEBUG_LOG]: 'Habilita logs de debug detalhados para o agente',
  [VSCODE_SETTINGS_KEYS.AGENT_FILE_LOGGING]: 'Habilita escrita de logs do agente em arquivo local',
  [VSCODE_SETTINGS_KEYS.TERMINAL_LINKS]: 'Links clicáveis para arquivos no terminal do Copilot CLI',
  [VSCODE_SETTINGS_KEYS.MCP_AUTOSTART]: 'Inicia automaticamente servidores MCP',
  [VSCODE_SETTINGS_KEYS.AGENT_MAX_REQUESTS]: 'Aumenta limite de requisições de agentes',
  [VSCODE_SETTINGS_KEYS.AGENT_ENABLED]: 'Habilita uso de agentes no chat',
  [VSCODE_SETTINGS_KEYS.SESSION_PROJECTION]: 'Habilita projeção de sessão do agente',
  [VSCODE_SETTINGS_KEYS.EXPLAIN_CHANGES]: 'Explica mudanças ao editar código',
  [VSCODE_SETTINGS_KEYS.EDIT_MODE_HIDDEN]: 'Oculta modo de edição quando inativo',
  [VSCODE_SETTINGS_KEYS.SKILL_ADHERENCE]: 'Força aderência aos prompts de skill',
  [VSCODE_SETTINGS_KEYS.TERMINAL_AUTO_REPLY]: 'Responde automaticamente prompts no terminal',
  [VSCODE_SETTINGS_KEYS.NESTED_AGENTS]: 'Habilita arquivos aninhados de agente',
  [VSCODE_SETTINGS_KEYS.AGENT_AUTO_FIX]: 'Auto-corrige erros encontrados pelo agente',
  [VSCODE_SETTINGS_KEYS.CODESEARCH_ENABLED]: 'Habilita busca de código avançada',
  [VSCODE_SETTINGS_KEYS.COPILOT_MEMORY]: 'Habilita memória de longo prazo do Copilot',
  [VSCODE_SETTINGS_KEYS.CUSTOM_AGENT_IN_SUBAGENT]: 'Habilita agentes customizados em subagentes',
  [VSCODE_SETTINGS_KEYS.USE_AGENT_SKILLS]: 'Habilita uso de Agent Skills do VS Code',
  [VSCODE_SETTINGS_KEYS.MEMORY_TOOLS_ENABLED]: 'Habilita acesso a ferramentas de memória do Copilot',
  [VSCODE_SETTINGS_KEYS.GITHUB_MCP_READONLY]: 'Servidor MCP do GitHub em modo leitura',
  [VSCODE_SETTINGS_KEYS.FIX_TYPESCRIPT]: 'Contexto específico para corrigir TypeScript',
  [VSCODE_SETTINGS_KEYS.SWITCH_AGENT]: 'Permite alternar entre agentes',
  [VSCODE_SETTINGS_KEYS.VIEW_SESSIONS_ORIENTATION]: 'Orientação empilhada para sessões de chat',
  [VSCODE_SETTINGS_KEYS.ENABLE_CHAT_TOOLS]: 'Habilita ferramentas de chat no navegador',
  [VSCODE_SETTINGS_KEYS.ADD_AI_COAUTHOR]: 'Adiciona co-autor de IA aos commits (chatAndAgent)',
  [VSCODE_SETTINGS_KEYS.REQUEST_QUEUING_DEFAULT]: 'Ação padrão ao enfileirar requisição',
  [VSCODE_SETTINGS_KEYS.THINKING_STYLE]: 'Estilo de pensamento do agente de chat',
  [VSCODE_SETTINGS_KEYS.THINKING_COLLAPSED_TOOLS]: 'Recolhe ferramentas de pensamento do agente',
  [VSCODE_SETTINGS_KEYS.THINKING_TERMINAL_TOOLS]: 'Ferramentas de terminal para o pensamento do agente',
  [VSCODE_SETTINGS_KEYS.AUTO_EXPAND_FAILURES]: 'Expande falhas de ferramentas automaticamente',
  [VSCODE_SETTINGS_KEYS.EXPLORE_AGENT_MODEL]: 'Modelo padrão para exploração do agente',
  [VSCODE_SETTINGS_KEYS.NOTIFY_ON_RESPONSE]: 'Notifica a janela ao receber resposta',
  [VSCODE_SETTINGS_KEYS.NOTIFY_ON_CONFIRMATION]: 'Notifica a janela em pedidos de confirmação',
  [VSCODE_SETTINGS_KEYS.PLUGINS_ENABLED]: 'Habilita o sistema de plugins do chat',
  [VSCODE_SETTINGS_KEYS.PLUGINS_MARKETPLACES]: 'Habilita marketplaces de plugins',
  [VSCODE_SETTINGS_KEYS.PLUGINS_PATHS]: 'Caminhos locais para plugins de chat',
  [VSCODE_SETTINGS_KEYS.FIND_CLOSE_ON_RESULT]: 'Fecha widget de busca após encontrar resultado',
  [VSCODE_SETTINGS_KEYS.PAGE_ZOOM]: 'Sincroniza zoom do browser com a janela principal',
  [VSCODE_SETTINGS_KEYS.AUTO_CHECK_UPDATES]: 'Verifica atualizações de extensões automaticamente',
  [VSCODE_SETTINGS_KEYS.FORMAT_ON_SAVE]: 'Formata o código automaticamente ao salvar',
  [VSCODE_SETTINGS_KEYS.BRACKET_COLORIZATION]: 'Colorização inteligente de pares de parênteses/chaves',
  [VSCODE_SETTINGS_KEYS.BRACKET_GUIDES]: 'Guias visuais para pares de colchetes/chaves',
  [VSCODE_SETTINGS_KEYS.INLINE_SUGGEST]: 'Habilita sugestões inline (fantasma) do Copilot',
  [VSCODE_SETTINGS_KEYS.COMPACT_FOLDERS]: 'Não compacta pastas vazias no explorador',
  [VSCODE_SETTINGS_KEYS.STARTUP_EDITOR]: 'Define qual editor abrir ao iniciar (none = limpo)'
};

/**
 * Configurações padrão sugeridas pela CLI.
 */
export const DEFAULT_ADVANCED_SETTINGS: Record<string, any> = {
  [VSCODE_SETTINGS_KEYS.AUTOPILOT_ENABLE]: true,
  [VSCODE_SETTINGS_KEYS.PARENT_CUSTOMIZATIONS]: true,
  [VSCODE_SETTINGS_KEYS.AGENT_DEBUG_LOG]: true,
  [VSCODE_SETTINGS_KEYS.AGENT_FILE_LOGGING]: true,
  [VSCODE_SETTINGS_KEYS.TERMINAL_LINKS]: true,
  [VSCODE_SETTINGS_KEYS.MCP_AUTOSTART]: "newAndOutdated",
  [VSCODE_SETTINGS_KEYS.AGENT_MAX_REQUESTS]: 1000,
  [VSCODE_SETTINGS_KEYS.AGENT_ENABLED]: true,
  [VSCODE_SETTINGS_KEYS.SESSION_PROJECTION]: true,
  [VSCODE_SETTINGS_KEYS.EXPLAIN_CHANGES]: true,
  [VSCODE_SETTINGS_KEYS.EDIT_MODE_HIDDEN]: true,
  [VSCODE_SETTINGS_KEYS.SKILL_ADHERENCE]: true,
  [VSCODE_SETTINGS_KEYS.TERMINAL_AUTO_REPLY]: true,
  [VSCODE_SETTINGS_KEYS.NESTED_AGENTS]: true,
  [VSCODE_SETTINGS_KEYS.AGENT_AUTO_FIX]: true,
  [VSCODE_SETTINGS_KEYS.CODESEARCH_ENABLED]: true,
  [VSCODE_SETTINGS_KEYS.COPILOT_MEMORY]: true,
  [VSCODE_SETTINGS_KEYS.CUSTOM_AGENT_IN_SUBAGENT]: true,
  [VSCODE_SETTINGS_KEYS.USE_AGENT_SKILLS]: true,
  [VSCODE_SETTINGS_KEYS.MEMORY_TOOLS_ENABLED]: true,
  [VSCODE_SETTINGS_KEYS.GITHUB_MCP_READONLY]: true,
  [VSCODE_SETTINGS_KEYS.FIX_TYPESCRIPT]: true,
  [VSCODE_SETTINGS_KEYS.SWITCH_AGENT]: true,
  [VSCODE_SETTINGS_KEYS.VIEW_SESSIONS_ORIENTATION]: "stacked",
  [VSCODE_SETTINGS_KEYS.ENABLE_CHAT_TOOLS]: true,
  [VSCODE_SETTINGS_KEYS.ADD_AI_COAUTHOR]: "chatAndAgent",
  [VSCODE_SETTINGS_KEYS.REQUEST_QUEUING_DEFAULT]: "steer",
  [VSCODE_SETTINGS_KEYS.THINKING_COLLAPSED_TOOLS]: "always",
  [VSCODE_SETTINGS_KEYS.THINKING_TERMINAL_TOOLS]: true,
  [VSCODE_SETTINGS_KEYS.AUTO_EXPAND_FAILURES]: true,
  [VSCODE_SETTINGS_KEYS.EXPLORE_AGENT_MODEL]: "GPT-5.4 (copilot)",
  [VSCODE_SETTINGS_KEYS.NOTIFY_ON_RESPONSE]: "windowNotFocused",
  [VSCODE_SETTINGS_KEYS.NOTIFY_ON_CONFIRMATION]: "windowNotFocused",
  [VSCODE_SETTINGS_KEYS.PLUGINS_PATHS]: [],
  [VSCODE_SETTINGS_KEYS.FIND_CLOSE_ON_RESULT]: true,
  [VSCODE_SETTINGS_KEYS.PAGE_ZOOM]: "100%",
  [VSCODE_SETTINGS_KEYS.AUTO_CHECK_UPDATES]: true,
  [VSCODE_SETTINGS_KEYS.FORMAT_ON_SAVE]: true,
  [VSCODE_SETTINGS_KEYS.BRACKET_COLORIZATION]: true,
  [VSCODE_SETTINGS_KEYS.BRACKET_GUIDES]: true,
  [VSCODE_SETTINGS_KEYS.INLINE_SUGGEST]: true,
  [VSCODE_SETTINGS_KEYS.COMPACT_FOLDERS]: false,
  [VSCODE_SETTINGS_KEYS.STARTUP_EDITOR]: "none"
};
