/**
 * Mapeamento centralizado de chaves de configuração do VS Code / Copilot.
 */
export const VSCODE_SETTINGS_KEYS = {
  INSTRUCTIONS: 'github.copilot.chat.codeGeneration.instructions',
  COPILOT_ENABLE: 'github.copilot.enable',
  PROMPT_LOCS: 'chat.promptFilesLocations',
  SKILLS_LOCS: 'chat.agentSkillsLocations',
  AGENTS_LOCS: 'chat.agentFilesLocations',
  AUTOPILOT_ENABLE: 'chat.autopilot.enabled',
  HOOK_LOCS: 'chat.hookFilesLocations',
  USE_HOOKS: 'chat.useCustomAgentHooks',
  COPILOT_HOOKS: 'github.copilot.chat.hooks',
  MCP_AUTOSTART: 'chat.mcp.autostart',
  AGENT_MAX_REQUESTS: 'chat.agent.maxRequests',
  AGENT_ENABLED: 'chat.agent.enabled',
  SESSION_PROJECTION: 'chat.agentSessionProjection.enabled',
  EXPLAIN_CHANGES: 'chat.editing.explainChanges.enabled',
  EDIT_MODE_HIDDEN: 'chat.editMode.hidden',
  SKILL_ADHERENCE: 'chat.experimental.useSkillAdherencePrompt',
  TERMINAL_AUTO_REPLY: 'chat.tools.terminal.autoReplyToPrompts',
  NESTED_AGENTS: 'chat.useNestedAgentsMdFiles',
  AGENT_AUTO_FIX: 'github.copilot.chat.agent.autoFix',
  CODESEARCH_ENABLED: 'github.copilot.chat.codesearch.enabled',
  COPILOT_MEMORY: 'github.copilot.chat.copilotMemory.enabled',
  MCP_GALLERY: 'chat.mcp.gallery.enabled',
  CUSTOM_AGENT_IN_SUBAGENT: 'chat.customAgentInSubagent.enabled',
  USE_AGENT_SKILLS: 'chat.useAgentSkills',
  GITHUB_MCP_READONLY: 'github.copilot.chat.githubMcpServer.readonly',
  FIX_TYPESCRIPT: 'github.copilot.chat.languageContext.fix.typescript.enabled',
  SWITCH_AGENT: 'github.copilot.chat.switchAgent.enabled',
  VIEW_SESSIONS_ORIENTATION: 'chat.viewSessions.orientation',
  ENABLE_CHAT_TOOLS: 'workbench.browser.enableChatTools',
  ADD_AI_COAUTHOR: 'git.addAICoAuthor',
  REQUEST_QUEUING: 'chat.requestQueuing.enabled',
  REQUEST_QUEUING_DEFAULT: 'chat.requestQueuing.defaultAction',
  THINKING_STYLE: 'chat.thinking.style',
  THINKING_COLLAPSED_TOOLS: 'chat.agent.thinking.collapsedTools',
  THINKING_TERMINAL_TOOLS: 'chat.agent.thinking.terminalTools',
  AUTO_EXPAND_FAILURES: 'chat.tools.autoExpandFailures',
  ASK_QUESTIONS: 'chat.askQuestions.enabled',
  HOOKS_ENABLED: 'chat.hooks.enabled',
  EXPLORE_AGENT_MODEL: 'chat.exploreAgent.defaultModel',
  NOTIFY_ON_RESPONSE: 'chat.notifyWindowOnResponseReceived',
  NOTIFY_ON_CONFIRMATION: 'chat.notifyWindowOnConfirmation',
  PLUGINS_ENABLED: 'chat.plugins.enabled',
  PLUGINS_MARKETPLACES: 'chat.plugins.marketplaces',
  PLUGINS_PATHS: 'chat.plugins.paths'
} as const;

export type VSCodeSettingKey = typeof VSCODE_SETTINGS_KEYS[keyof typeof VSCODE_SETTINGS_KEYS];

/**
 * Descrições amigáveis para os logs de diff.
 */
export const SETTING_DESCRIPTIONS: Record<string, string> = {
  [VSCODE_SETTINGS_KEYS.INSTRUCTIONS]: 'Instruções globais de geração de código para o Copilot',
  [VSCODE_SETTINGS_KEYS.COPILOT_ENABLE]: 'Habilita/desabilita o Copilot por linguagem',
  [VSCODE_SETTINGS_KEYS.PROMPT_LOCS]: 'Pastas adicionais contendo arquivos de prompt (.prompt.md)',
  [VSCODE_SETTINGS_KEYS.SKILLS_LOCS]: 'Pastas contendo definições de Agent Skills',
  [VSCODE_SETTINGS_KEYS.AGENTS_LOCS]: 'Pastas contendo definições de Agentes customizados',
  [VSCODE_SETTINGS_KEYS.AUTOPILOT_ENABLE]: 'Habilita o modo Autopilot no VS Code',
  [VSCODE_SETTINGS_KEYS.HOOK_LOCS]: 'Pastas contendo hooks para o Copilot',
  [VSCODE_SETTINGS_KEYS.USE_HOOKS]: 'Habilita o uso de hooks customizados',
  [VSCODE_SETTINGS_KEYS.COPILOT_HOOKS]: 'Hooks de execução de comandos (PreToolUse/PostToolUse)',
  [VSCODE_SETTINGS_KEYS.MCP_AUTOSTART]: 'Inicia automaticamente servidores MCP',
  [VSCODE_SETTINGS_KEYS.AGENT_MAX_REQUESTS]: 'Aumenta limite de requisições de agentes',
  [VSCODE_SETTINGS_KEYS.AGENT_ENABLED]: 'Habilita uso de agentes no chat',
  [VSCODE_SETTINGS_KEYS.SESSION_PROJECTION]: 'Habilita projeção de sessão do agente',
  [VSCODE_SETTINGS_KEYS.EXPLAIN_CHANGES]: 'Explica mudanças ao editar código',
  [VSCODE_SETTINGS_KEYS.EDIT_MODE_HIDDEN]: 'Oculta modo de edição quando inativo',
  [VSCODE_SETTINGS_KEYS.SKILL_ADHERENCE]: 'Força aderência aos prompts de skill',
  [VSCODE_SETTINGS_KEYS.TERMINAL_AUTO_REPLY]: 'Responde automaticamente prompts no terminal',
  [VSCODE_SETTINGS_KEYS.NESTED_AGENTS]: 'Habilita arquivos aninhados de agente',
  [VSCODE_SETTINGS_KEYS.AGENT_AUTO_FIX]: 'Auto-corrige erros encontrados pelo agente',
  [VSCODE_SETTINGS_KEYS.CODESEARCH_ENABLED]: 'Habilita busca de código avançada',
  [VSCODE_SETTINGS_KEYS.COPILOT_MEMORY]: 'Habilita memória de longo prazo do Copilot',
  [VSCODE_SETTINGS_KEYS.MCP_GALLERY]: 'Habilita galeria de servidores MCP',
  [VSCODE_SETTINGS_KEYS.CUSTOM_AGENT_IN_SUBAGENT]: 'Habilita agentes customizados em subagentes',
  [VSCODE_SETTINGS_KEYS.USE_AGENT_SKILLS]: 'Habilita uso de Agent Skills do VS Code',
  [VSCODE_SETTINGS_KEYS.GITHUB_MCP_READONLY]: 'Servidor MCP do GitHub em modo leitura',
  [VSCODE_SETTINGS_KEYS.FIX_TYPESCRIPT]: 'Contexto específico para corrigir TypeScript',
  [VSCODE_SETTINGS_KEYS.SWITCH_AGENT]: 'Permite alternar entre agentes',
  [VSCODE_SETTINGS_KEYS.VIEW_SESSIONS_ORIENTATION]: 'Orientação empilhada para sessões de chat',
  [VSCODE_SETTINGS_KEYS.ENABLE_CHAT_TOOLS]: 'Habilita ferramentas de chat no navegador',
  [VSCODE_SETTINGS_KEYS.ADD_AI_COAUTHOR]: 'Adiciona co-autor de IA aos commits (chatAndAgent)',
  [VSCODE_SETTINGS_KEYS.REQUEST_QUEUING]: 'Habilita fila de requisições para o chat',
  [VSCODE_SETTINGS_KEYS.REQUEST_QUEUING_DEFAULT]: 'Ação padrão ao enfileirar requisição',
  [VSCODE_SETTINGS_KEYS.THINKING_STYLE]: 'Estilo de pensamento do agente de chat',
  [VSCODE_SETTINGS_KEYS.THINKING_COLLAPSED_TOOLS]: 'Recolhe ferramentas de pensamento do agente',
  [VSCODE_SETTINGS_KEYS.THINKING_TERMINAL_TOOLS]: 'Ferramentas de terminal para o pensamento do agente',
  [VSCODE_SETTINGS_KEYS.AUTO_EXPAND_FAILURES]: 'Expande falhas de ferramentas automaticamente',
  [VSCODE_SETTINGS_KEYS.ASK_QUESTIONS]: 'Habilita o agente a fazer perguntas de clarificação',
  [VSCODE_SETTINGS_KEYS.HOOKS_ENABLED]: 'Habilita o sistema de hooks de chat',
  [VSCODE_SETTINGS_KEYS.EXPLORE_AGENT_MODEL]: 'Modelo padrão para exploração do agente',
  [VSCODE_SETTINGS_KEYS.NOTIFY_ON_RESPONSE]: 'Notifica a janela ao receber resposta',
  [VSCODE_SETTINGS_KEYS.NOTIFY_ON_CONFIRMATION]: 'Notifica a janela em pedidos de confirmação',
  [VSCODE_SETTINGS_KEYS.PLUGINS_ENABLED]: 'Habilita o sistema de plugins do chat',
  [VSCODE_SETTINGS_KEYS.PLUGINS_MARKETPLACES]: 'Habilita marketplaces de plugins',
  [VSCODE_SETTINGS_KEYS.PLUGINS_PATHS]: 'Caminhos locais para plugins de chat',
  "privateExtensions.registries": "Registries privados para extensões"
};

/**
 * Configurações padrão sugeridas pela CLI.
 */
export const DEFAULT_ADVANCED_SETTINGS: Record<string, any> = {
  [VSCODE_SETTINGS_KEYS.MCP_AUTOSTART]: "newAndOutdated",
  [VSCODE_SETTINGS_KEYS.AGENT_MAX_REQUESTS]: 1000,
  [VSCODE_SETTINGS_KEYS.AGENT_ENABLED]: true,
  [VSCODE_SETTINGS_KEYS.SESSION_PROJECTION]: true,
  [VSCODE_SETTINGS_KEYS.EXPLAIN_CHANGES]: true,
  [VSCODE_SETTINGS_KEYS.EDIT_MODE_HIDDEN]: true,
  [VSCODE_SETTINGS_KEYS.SKILL_ADHERENCE]: true,
  [VSCODE_SETTINGS_KEYS.TERMINAL_AUTO_REPLY]: true,
  [VSCODE_SETTINGS_KEYS.NESTED_AGENTS]: true,
  [VSCODE_SETTINGS_KEYS.AGENT_AUTO_FIX]: true,
  [VSCODE_SETTINGS_KEYS.CODESEARCH_ENABLED]: true,
  [VSCODE_SETTINGS_KEYS.COPILOT_MEMORY]: true,
  [VSCODE_SETTINGS_KEYS.MCP_GALLERY]: true,
  [VSCODE_SETTINGS_KEYS.CUSTOM_AGENT_IN_SUBAGENT]: true,
  [VSCODE_SETTINGS_KEYS.USE_AGENT_SKILLS]: true,
  [VSCODE_SETTINGS_KEYS.GITHUB_MCP_READONLY]: true,
  [VSCODE_SETTINGS_KEYS.FIX_TYPESCRIPT]: true,
  [VSCODE_SETTINGS_KEYS.SWITCH_AGENT]: true,
  [VSCODE_SETTINGS_KEYS.VIEW_SESSIONS_ORIENTATION]: "stacked",
  [VSCODE_SETTINGS_KEYS.ENABLE_CHAT_TOOLS]: true,
  [VSCODE_SETTINGS_KEYS.ADD_AI_COAUTHOR]: "chatAndAgent",
  [VSCODE_SETTINGS_KEYS.REQUEST_QUEUING]: true,
  [VSCODE_SETTINGS_KEYS.REQUEST_QUEUING_DEFAULT]: "ask",
  [VSCODE_SETTINGS_KEYS.THINKING_STYLE]: "compact",
  [VSCODE_SETTINGS_KEYS.THINKING_COLLAPSED_TOOLS]: true,
  [VSCODE_SETTINGS_KEYS.THINKING_TERMINAL_TOOLS]: true,
  [VSCODE_SETTINGS_KEYS.AUTO_EXPAND_FAILURES]: true,
  [VSCODE_SETTINGS_KEYS.ASK_QUESTIONS]: true,
  [VSCODE_SETTINGS_KEYS.HOOKS_ENABLED]: true,
  [VSCODE_SETTINGS_KEYS.EXPLORE_AGENT_MODEL]: "GPT-5.4 (copilot)",
  [VSCODE_SETTINGS_KEYS.NOTIFY_ON_RESPONSE]: true,
  [VSCODE_SETTINGS_KEYS.NOTIFY_ON_CONFIRMATION]: true,
  [VSCODE_SETTINGS_KEYS.PLUGINS_ENABLED]: true,
  [VSCODE_SETTINGS_KEYS.PLUGINS_MARKETPLACES]: true,
  [VSCODE_SETTINGS_KEYS.PLUGINS_PATHS]: []
};
