# Sonar Properties Template

```properties
sonar.host.url=https://sonarqube.luizalabs.com
sonar.projectName={APPNAME}
sonar.projectKey={APPNAME}
sonar.projectVersion=0.1.0
sonar.sources=app
sonar.language=py
sonar.sourceEncoding=UTF-8
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**test_**,**conftest**,**settings**
sonar.coverage.exclusions=**test_**,**conftest**,**settings**
```
