# SonarQube Template
sonar.projectKey={APPNAME}
sonar.projectName={APPNAME}
sonar.projectVersion=1.0.0

# Paths to source code and tests
sonar.sources=src
sonar.tests=test

# Language specific settings (Adjust according to the stack)
# sonar.language=py

# Coverage and exclusions
sonar.exclusions=**/node_modules/**,**/*.spec.*,**/*.test.*,**/dist/**,**/build/**
sonar.test.inclusions=**/*.spec.*,**/*.test.*
# sonar.python.coverage.reportPaths=coverage.xml
# sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Quality Gate
sonar.qualitygate.wait=true
